.PHONY: dev
dev: kubeconfig.yaml
dev: KUBECONFIG = $(PWD)/kubeconfig.yaml
dev: NAMESPACE := default
dev: NODE_NAME := vkubelet-browser
dev: PROFILE := local
dev: export VK_BUILD_TAGS += browser_provider
dev: dev.recreate skaffold/dev


.PHONY: dev.recreate
dev.recreate: skaffold/delete
	kubectl delete --ignore-not-found node $(NODE_NAME); \