apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "vkubelet-browser"
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "36000"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: "vkubelet-browser"
              servicePort: 80
