apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-browser
  labels:
    app: vkubelet-browser
spec:
  containers:
    - name: vkubelet-browser
      image: virtual-kubelet
      # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
      imagePullPolicy: IfNotPresent
      args:
        - /virtual-kubelet
        - --nodename
        - vkubelet-browser
        - --provider
        - browser
        - --provider-config
        - /vkubelet-browser-cfg.json
        - --startup-timeout
        - 10s
        - --klog.v
        - "2"
        - --klog.logtostderr
        - --log-level
        - debug
      env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: API_PORT
          value: "80"
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      ports:
        - name: api
          containerPort: 80
      readinessProbe:
        httpGet:
          path: /pods
          port: api
      volumeMounts:
        - name: images
          mountPath: /browser-kube-images
    - name: docker-in-docker
      image: docker:20.10.2-dind
      args:
        - --host=tcp://0.0.0.0:2375
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      ports:
        - containerPort: 2375
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: images
      emptyDir: {}
  serviceAccountName: virtual-kubelet
