apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
    - image: virtual-kubelet
      docker:
        dockerfile: hack/skaffold/virtual-kubelet/Dockerfile
        buildArgs:
          VERSION: "{{.VERSION}}"
          BUILD_TIME: "{{.BUILD_TIME}}"
deploy:
  kubectl:
    manifests:
      - hack/skaffold/virtual-kubelet/base.yml
      - hack/skaffold/virtual-kubelet/pod.yml
profiles:
  - name: local
    build:
      local: {}
